export const  COUNTRY_USER_SAVED="COUNTRY_USER_SAVED";
export const  ID_USER_SAVED="ID_USER_SAVED";
export const  RUN_A_STEP="RUN_A_STEP";
export const DEATAILS_USER_SAVED="DEATAILS_USER_SAVED";
export const DEATAILS_MARATON_USER_SAVED="DEATAILS_MARATON_USER_SAVED";
export const DEATAILS_RULLS_USER_SAVED="DEATAILS_RULLS_USER_SAVED";
export const KIND_MARATON_SAVED="KIND_MARATON_SAVED";




